name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: poetry install
      run: |
        curl -sSL https://install.python-poetry.org | python -
        $HOME/.local/bin/poetry install
    - name: black
      run: |
        $HOME/.local/bin/poetry run black --check --line-length 120 .
    - name: pytest
      run: |
        $HOME/.local/bin/poetry run pytest tests
